### ISSUE TITLE
怎么初始化一个vue+vux APP，请问

### ISSUE THREAD

**Issue by ljhzds** [givebest/vue-vux-demo#1]

**Comment by givebest** [comment]
听不明白你的问题？

创建 vue  实例

    new Vue({})

**Comment by ljhzds** [comment]
谢谢，我想问的是怎么新建一个vue + vue-router + vuex + vue-resource的工程。
然后我去查了下文档，稍微入手了下，
像你这种比较大一点的工程还要研究。。

**Comment by givebest** [comment]
看下`vux`官方文档：[https://vux.li/#/zh-CN/README?id=%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8](https://vux.li/#/zh-CN/README?id=%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8) 

    npm install vue-cli -g // 如果还没安装

    vue init airyland/vux2 projectPath


    cd projectPath

    npm install // 使用 cnpm 安装可能会出现问题，推荐使用 npm --
    registry=https://registry.npm.taobao.org

    npm run dev
